apiVersion: volume.hcloud.crossplane.io/v1alpha1
kind: Attachment
metadata:
  annotations:
    meta.upbound.io/example-id: volume/v1alpha1/attachment
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    automount: true
    serverIdSelector:
      matchLabels:
        testing.upbound.io/example-name: node1
    volumeIdSelector:
      matchLabels:
        testing.upbound.io/example-name: master

---

apiVersion: server.hcloud.crossplane.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: volume/v1alpha1/attachment
  labels:
    testing.upbound.io/example-name: node1
  name: node1
spec:
  forProvider:
    datacenter: nbg1-dc3
    image: debian-11
    name: node1
    serverType: cx22

---

apiVersion: volume.hcloud.crossplane.io/v1alpha1
kind: Volume
metadata:
  annotations:
    meta.upbound.io/example-id: volume/v1alpha1/attachment
  labels:
    testing.upbound.io/example-name: master
  name: master
spec:
  forProvider:
    location: nbg1
    size: 10
