apiVersion: volume.hcloud.crossplane.io/v1alpha1
kind: Volume
metadata:
  annotations:
    meta.upbound.io/example-id: volume/v1alpha1/volume
  labels:
    testing.upbound.io/example-name: master
  name: master
spec:
  forProvider:
    automount: true
    format: ext4
    name: volume1
    serverIdSelector:
      matchLabels:
        testing.upbound.io/example-name: node1
    size: 50

---

apiVersion: server.hcloud.crossplane.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: volume/v1alpha1/volume
  labels:
    testing.upbound.io/example-name: node1
  name: node1
spec:
  forProvider:
    image: debian-11
    name: node1
    serverType: cx22
