apiVersion: hcloud.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: hcloud
spec:
  credentials:
    source: Secret
    secretRef:
      name: hcloud-creds
      namespace: crossplane-system
      key: credentials
