apiVersion: floatingip.hcloud.crossplane.io/v1alpha1
kind: IPAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: floatingip/v1alpha1/ipassignment
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    floatingIpIdSelector:
      matchLabels:
        testing.upbound.io/example-name: master
    serverId: ${hcloud_server.node1.id}

---

apiVersion: floatingip.hcloud.crossplane.io/v1alpha1
kind: IP
metadata:
  annotations:
    meta.upbound.io/example-id: floatingip/v1alpha1/ipassignment
  labels:
    testing.upbound.io/example-name: master
  name: master
spec:
  forProvider:
    homeLocation: nbg1
    type: ipv4

---

apiVersion: server.hcloud.crossplane.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: floatingip/v1alpha1/ipassignment
  labels:
    testing.upbound.io/example-name: node1
  name: node1
spec:
  forProvider:
    datacenter: fsn1-dc8
    image: debian-11
    name: node1
    serverType: cx22
