apiVersion: sshkey.hcloud.crossplane.io/v1alpha1
kind: Key
metadata:
  annotations:
    meta.upbound.io/example-id: sshkey/v1alpha1/key
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    name: my-ssh-key
    publicKey: ${file("~/.ssh/id_ed25519.pub")}
